name: Issue-Comment Workflow

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github Actions
        run: echo '${{ toJSON (github.event) }}'| jq
        shell: bash
